Final Touches
Diegogagan2587/Leaderboard pull request #3
Opened 2023-06-23 00:25 UTC by Diegogagan2587

# Implemented Changes:

- Add background color
- Add borders for the header and for each section like Recent Scores and Add your score
- set the color of the text to blue:
- Set the background color for the header and score section to azure;
- Add a hover Effect for all buttons.

2023-06-23 00:36 UTC, 1GORDON reviewed
##
## Hi @Diegogagan2587 ✋

Good job so far!

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!_

### This project will be marked as Invalid and won't affect the number of your weekly reviews.

- [x] Kindly remove the live demo section from your readme file since this project is not deployed.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 01:00 UTC, Reem-lab requested changes
# Hi @Diegogagan2587, 👋🏻👋🏻

Great job so far! 🚀✨💯🔥
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media0.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy-downsized-medium.gif"/>

## Highlights
- Followed Gitflow 💯🚀
- Great job working on the styles⭐
- No linters error 💯🚀✨
- Professional README 💪🏻
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-23 01:00 UTC, Reem-lab commented on src/style.css
> +
- [x] Great job working on the design but I think it would be great if you made the form as the given wireframe regarding to the layout of the heading and the inputs and the submit button so I highly recommend to improve it to match the wireframe ⭐🔥💪🏻

- Kindly make the heading close to the form 🔥
- Kindly make the button have small width like the given wireframe ⭐

- Your
![image](https://github.com/Diegogagan2587/Leaderboard/assets/58553711/38b243f5-7d59-4208-bb3d-a3f55a3e8c05)


- Given
![image](https://github.com/Diegogagan2587/Leaderboard/assets/58553711/1765e833-454c-48ed-8cbe-cba06b5bbfb6)

2023-06-23 01:00 UTC, Reem-lab commented on src/style.css
> +  height: 10vw;
- [ ] I think it would be great if you make scores list style the same as the given wireframe since in the given wireframe each score has more padding and different colors like grey and white in order so kindly make it as much as possible as the given wireframe ⭐💪🏻🔥

- yours
![image](https://github.com/Diegogagan2587/Leaderboard/assets/58553711/faba4e17-a977-47d2-b2da-68f3c3b79e47)

- Given
![image](https://github.com/Diegogagan2587/Leaderboard/assets/58553711/3ca353da-99d1-4910-bc33-823a2a3a3219)

2023-06-24 00:46 UTC, merged

2023-06-24 00:47 UTC, Efiamotu-1 approved these changes
Hi @Diegogagan2587 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![giphy](https://user-images.githubusercontent.com/89055502/234114221-4ca295de-fd8f-4af6-9c49-a6d4c6ea67f7.gif)


## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-24 00:47 UTC, Efiamotu-1 commented on src/style.css
- [ ] [OPTIONAL] You could try to sort the data in descending order so that the highest scores are top of the pile and it is easier to notice the highest scoring players. I believe this will make your project even better 👍

2023-06-24 00:47 UTC, Efiamotu-1 commented on src/style.css
- [ ] [OPTIONAL] Also after clicking submit the form fields should be cleared to show users that thre forms have been added. I believe this will make your project even better 👍